name: Libfstcpp Regression Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  regression:
    name: Build and Run Regression
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential ninja-build libgtest-dev lcov

      - name: Run tests
        run: ./run_regression.sh --coverage

      - name: Comment Link on Commit
        if: false
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"

          if [ "${{ job.status }}" == "success" ]; then
            ICON="✅"
          else
            ICON="❌"
          fi

          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/comments \
            -f body="$ICON **Regression Report:** [Click Here to View Summary]($URL)"
